export const KPM_DATA = {
  'Prasekolah': {
    'Bahasa Cina': ['Kenal Huruf (认识字母)', 'Kenal Nombor (认识数字)', 'Kemahiran Mendengar dan Bertutur (Cina)', 'Kemahiran Membaca (Cina)', 'Kemahiran Menulis (Cina)'],
    'Bahasa Melayu': ['Kemahiran Mendengar dan Bertutur', 'Kemahiran Membaca', 'Kemahiran Menulis'],
    'Bahasa Inggeris': ['Listening and Speaking', 'Reading', 'Writing'],
    'Matematik Awal': ['Pengalaman Pranombor', 'Konsep Nombor', 'Operasi Nombor', 'Nilai Wang', 'Masa dan Waktu', 'Bentuk dan Ruang'],
    'Sains Awal': ['Sikap Saintifik', 'Kemahiran Saintifik', 'Menyiasat Alam Hidupan', 'Menyiasat Alam Bahan', 'Menyiasat Alam Fizikal'],
    'Pendidikan Islam': ['Al-Quran (Huruf Hijaiyah & Hafazan)', 'Akidah (Rukun Iman, Rukun Islam)', 'Ibadah (Bersuci, Wuduk, Solat, Puasa)', 'Sirah (Sirah Nabi Muhammad SAW)', 'Akhlak (Adab Harian)', 'Jawi (Huruf Jawi & Suku Kata)'],
    'Pendidikan Moral': ['Kepercayaan kepada Tuhan', 'Baik Hati', 'Bertanggungjawab', 'Berterima Kasih', 'Hemah Tinggi', 'Hormat', 'Kasih Sayang', 'Keadilan', 'Keberanian', 'Kejujuran', 'Kerajinan', 'Kerjasama', 'Kesederhanaan', 'Toleransi'],
    'Keterampilan Diri': ['Mengenali dan Mengurus Emosi Sendiri', 'Membina Kemahiran Sosial'],
    'Perkembangan Fizikal & Kesihatan': ['Perkembangan Motor Halus', 'Perkembangan Motor Kasar', 'Kemahiran Manipulasi', 'Pergerakan Berirama', 'Pendidikan Kesihatan (PEERS)', 'Pemakanan', 'Keselamatan'],
    'Kreativiti dan Estetika': ['Seni Visual', 'Muzik dan Nyanyian', 'Drama / Lakonan'],
    'Kemanusiaan': ['Saya dan Keluarga', 'Saya dan Komuniti', 'Saya dan Negara', 'Saya dan Alam Sekitar']
  },
  'Tahun 1 (KSSR)': {
    'Bahasa Cina': ['Keluarga Saya (我的家庭)', 'Sekolah Saya (我的学校)', 'Kawan Saya (我的朋友)', 'Haiwan (动物)'],
    'Bahasa Melayu': ['Tema 1: Keluarga Penyayang', 'Tema 2: Masyarakat Muhibah', 'Tema 3: Kebersihan dan Kesihatan', 'Tema 4: Keselamatan', 'Tema 5: Negaraku Tercinta', 'Tema 6: Sains, Teknologi dan Inovasi', 'Tema 7: Lindungi Alam', 'Tema 8: Ekonomi dan Kewangan'],
    'Bahasa Inggeris': ['Phonics', 'Intro: Friends', 'Unit 1: At School', 'Unit 2: Let\'s Play!', 'Unit 3: Pet Show', 'Unit 4: Lunchtime'],
    'Matematik': ['Nombor hingga 100', 'Tambah dan Tolak', 'Pecahan', 'Wang', 'Masa dan Waktu', 'Ukuran dan Sukatan', 'Bentuk', 'Data'],
    'Sains': ['Kemahiran Saintifik', 'Peraturan Bilik Sains', 'Benda Hidup dan Benda Bukan Hidup', 'Manusia (Deria)', 'Haiwan (Bahagian Tubuh)', 'Tumbuh-tumbuhan (Bahagian Tumbuhan)', 'Magnet', 'Penyerapan', 'Bumi', 'Asas Binaan'],
    'Pendidikan Islam': ['Al-Quran: Huruf Hijaiyah Berbaris', 'Al-Quran: Bacaan Tanwin & Izhar', 'Al-Quran: Bacaan Lin & Bertasydid', 'Al-Quran: Mad & Tanda Waqaf', 'Hafazan: Surah Al-Fatihah & Al-Ikhlas', 'Jawi: Dunia Keindahan & Alamku Ceria', 'Jawi: Kedai Kek Ummi & Di Pasar Raya', 'Jawi: Sekolahku Gemilang', 'Akidah: Iman Peganganku', 'Akidah: Islam Cara Hidupku', 'Akidah: Tuhanku Ar-Rahman Ar-Rahim', 'Ibadah: Air Dalam Kehidupan', 'Ibadah: Kebersihan Amalanku & Wuduk', 'Ibadah: Solat Tiang Agama', 'Sirah: Kelahiran Kekasih Allah', 'Sirah: Teladani Sifat Siddiq Nabi Muhammad SAW', 'Adab: Bersih Diri Hiasi Peribadi', 'Adab: Keluargaku Sayang', 'Adab: Zikir Penenang Jiwa'],
    'Pendidikan Jasmani dan Pendidikan Kesihatan': ['Konsep Pergerakan', 'Pergerakan Asas (Lokomotor & Bukan Lokomotor)', 'Kemahiran Manipulasi Alatan', 'Pergerakan Berirama', 'Gimnastik Asas', 'Akuatik Asas / Keselamatan Air', 'Rekreasi dan Kesenggangan', 'Kecergasan Fizikal', 'Kesihatan Diri dan Reproduktif (PEERS)', 'Pemakanan Sihat', 'Pertolongan Cemas'],
    'Pendidikan Seni Visual dan Pendidikan Muzik': ['Menggambar', 'Membuat Corak dan Rekaan', 'Membentuk dan Membuat Binaan', 'Mengenal Kraf Tradisional', 'Pengalaman Muzikal', 'Penghasilan Muzik', 'Apresiasi Muzik'],
    'Bahasa Arab': ['Huruf Hijaiah', 'Taaruf (Perkenalan)', 'Peralatan Sekolah', 'Nombor dan Bilangan (1-10)']
  },
  'Tahun 2 (KSSR)': {
    'Bahasa Cina': ['Aktiviti Harian (日常活动)', 'Hobi (爱好)', 'Makanan (食物)', 'Masa dan Waktu (时间)'],
    'Bahasa Melayu': ['Keluarga Saya', 'Kisah Kejayaan', 'Sains dan Teknologi', 'Alam Sekitar', 'Budaya Bangsa'],
    'Bahasa Inggeris': ['Free Time', 'The Old House', 'Get Dressed', 'The Robot', 'At the Beach'],
    'Matematik': ['Nombor hingga 1000', 'Tambah, Tolak, Darab, Bahagi', 'Pecahan dan Perpuluhan', 'Wang', 'Masa dan Waktu', 'Ukuran dan Sukatan', 'Bentuk', 'Pengurusan Data'],
    'Sains': ['Kemahiran Saintifik', 'Peraturan Bilik Sains', 'Manusia (Pembiakan dan Tumbesaran)', 'Haiwan (Pembiakan dan Tumbesaran)', 'Tumbuh-tumbuhan (Tumbesaran)', 'Terang dan Gelap', 'Litar Elektrik', 'Campuran', 'Bumi dan Angkasa', 'Teknologi'],
    'Pendidikan Islam': ['Al-Quran: Surah An-Nas dan Al-Falaq', 'Tajwid: Hukum Mad Asli & Ghunnah', 'Jawi: Perkataan Tiga Suku Kata atau Lebih', 'Jawi: Membaca Petikan Pendek', 'Akidah: Kenali Sifat-Sifat Allah', 'Akidah: Tuhanku Al-Ahad dan As-Samad', 'Akidah: Malaikat yang Setia', 'Ibadah: Diriku Bersih', 'Ibadah: Solatku Sempurna', 'Ibadah: Bacaan Wajib & Sunat Solatku', 'Sirah: Sesuci Hati Kekasih Allah', 'Sirah: Nabi Muhammad SAW Al-Amin', 'Sirah: Nabi Muhammad SAW Sahabat Sejati', 'Adab: Berkati Rezekiku', 'Adab: Indahnya Persahabatan', 'Adab: Adab Berdoa'],
    'Pendidikan Jasmani dan Pendidikan Kesihatan': ['Konsep Pergerakan', 'Pergerakan Asas', 'Kemahiran Manipulasi Alatan', 'Pergerakan Berirama', 'Gimnastik Asas', 'Akuatik Asas', 'Rekreasi dan Kesenggangan', 'Kecergasan Fizikal', 'Kesihatan Diri dan Reproduktif (PEERS)', 'Pemakanan Sihat', 'Pertolongan Cemas'],
    'Pendidikan Seni Visual dan Pendidikan Muzik': ['Menggambar', 'Membuat Corak dan Rekaan', 'Membentuk dan Membuat Binaan', 'Mengenal Kraf Tradisional', 'Pengalaman Muzikal', 'Penghasilan Muzik', 'Apresiasi Muzik'],
    'Bahasa Arab': ['Keluarga Saya', 'Anggota Badan', 'Peralatan Sekolah', 'Nombor dan Bilangan (11-20)']
  },
  'Tahun 3 (KSSR)': {
    'Bahasa Cina': ['Alam Sekitar (环境)', 'Kebersihan (卫生)', 'Perayaan (节日)', 'Cita-cita (志愿)'],
    'Bahasa Melayu': ['Keluarga Bahagia', 'Hidup Sejahtera', 'Sayangi Alam Sekitar', 'Keselamatan', 'Kebudayaan'],
    'Bahasa Inggeris': ['Welcome!', 'Everyday', 'Right Now', 'Year in, Year Out', 'My New House', 'Food, Please!', 'Out and About', 'On Holiday'],
    'Matematik': ['Nombor hingga 10 000', 'Operasi Asas', 'Pecahan, Perpuluhan dan Peratus', 'Wang', 'Masa dan Waktu', 'Ukuran dan Sukatan', 'Bentuk', 'Kedudukan', 'Data'],
    'Sains': ['Kemahiran Saintifik', 'Peraturan Bilik Sains', 'Manusia (Gigi, Kelas Makanan, Pencernaan)', 'Haiwan (Tabiat Pemakanan)', 'Tumbuh-tumbuhan (Pembiakan)', 'Pengukuran', 'Ketumpatan', 'Asid dan Alkali', 'Sistem Suria', 'Mesin'],
    'Pendidikan Islam': ['Al-Quran: Surah Al-Kafirun & Al-Asr', 'Tajwid: Hukum Nun Sakinah & Tanwin', 'Jawi: Imbuhan Awalan & Akhiran', 'Akidah: Beriman Kepada Kitab', 'Akidah: Nama Allah Al-Alim & Al-Hakim', 'Ibadah: Bersuci Daripada Hadas Besar', 'Ibadah: Solat Sunat Rawatib', 'Sirah: Penerimaan Wahyu Pertama', 'Sirah: Keperibadian Nabi Muhammad', 'Adab: Menuntut Ilmu', 'Adab: Tidur Yang Berkualiti', 'Adab: Bersyukur'],
    'Pendidikan Jasmani dan Pendidikan Kesihatan': ['Kemahiran Pergerakan Asas', 'Pergerakan Berirama', 'Gimnastik Asas', 'Olahraga Asas', 'Akuatik Asas', 'Rekreasi dan Kesenggangan', 'Kecergasan Fizikal', 'Kesihatan Diri dan Reproduktif (PEERS)', 'Pemakanan Sihat', 'Pertolongan Cemas'],
    'Pendidikan Seni Visual dan Pendidikan Muzik': ['Menggambar', 'Membuat Corak dan Rekaan', 'Membentuk dan Membuat Binaan', 'Mengenal Kraf Tradisional', 'Pengalaman Muzikal', 'Penghasilan Muzik', 'Apresiasi Muzik'],
    'Bahasa Arab': ['Pakaian', 'Warna', 'Hari dan Bulan', 'Nombor dan Bilangan (21-31)']
  },
  'Tahun 4 (KSSR)': {
    'Bahasa Cina': ['Sains dan Teknologi (科学与科技)', 'Seni dan Budaya (艺术与文化)', 'Kesihatan (健康)', 'Keselamatan (安全)'],
    'Bahasa Melayu': ['Tema: Kemasyarakatan', 'Tema: Kesihatan dan Kebersihan', 'Tema: Keselamatan', 'Tema: Kebudayaan, Kesenian dan Estetika', 'Tema: Alam Sekitar dan Teknologi Hijau'],
    'Bahasa Inggeris': ['Where are you from?', 'My week', 'In the past', 'Celebrations', 'Eating right', 'Getting around', 'Helping out', 'Amazing animals', 'Get active!', 'What\'s the matter?'],
    'Matematik': ['Nombor dan Operasi (hingga 100,000)', 'Pecahan, Perpuluhan dan Peratus', 'Wang', 'Masa dan Waktu', 'Ukuran dan Sukatan', 'Ruang', 'Koordinat, Nisbah dan Kadaran', 'Pengurusan Data'],
    'Sains': ['Kemahiran Saintifik', 'Manusia (Pernafasan, Perkumuhan, Penyahtinjaan, Gerak Balas)', 'Haiwan (Organ Pernafasan, Vertebrata)', 'Tumbuh-tumbuhan (Gerak Balas, Fotosintesis)', 'Sifat Cahaya', 'Bunyi', 'Tenaga', 'Bahan', 'Bumi', 'Mesin'],
    'Pendidikan Islam': ['Al-Quran: Surah At-Takathur & Al-Qariah', 'Tajwid: Hukum Mim Sakinah', 'Jawi: Tanda Baca & Khat Nasakh', 'Akidah: Beriman Kepada Rasul', 'Akidah: Nama Allah Al-Azim & Al-Hamid', 'Ibadah: Mari Bersuci', 'Ibadah: Puasa Bulan Ramadan', 'Sirah: Perjanjian Aqabah', 'Sirah: Hijrah Ke Madinah', 'Adab: Adab Berjiran', 'Adab: Adab Di Masjid'],
    'Sejarah': ['Mengenali Sejarah', 'Zaman Air Batu', 'Zaman Prasejarah', 'Kerajaan Melayu Awal', 'Tokoh Terbilang Kesultanan Melayu Melaka'],
    'Reka Bentuk dan Teknologi': ['Keselamatan Bengkel', 'Pengenalan Reka Bentuk', 'Reka Bentuk Pembungkusan', 'Reka Bentuk Pengaturcaraan'],
    'Pendidikan Jasmani dan Pendidikan Kesihatan': ['Kemahiran Asas Permainan (Serangan, Jaring, Memadang)', 'Olahraga Asas', 'Gimnastik Asas', 'Pergerakan Berirama', 'Akuatik Asas', 'Rekreasi dan Kesenggangan', 'Kecergasan Fizikal', 'Kesihatan Diri dan Reproduktif (PEERS)', 'Pemakanan Sihat', 'Pertolongan Cemas'],
    'Pendidikan Seni Visual dan Pendidikan Muzik': ['Menggambar', 'Membuat Corak dan Rekaan', 'Membentuk dan Membuat Binaan', 'Mengenal Kraf Tradisional', 'Pengalaman Muzikal', 'Penghasilan Muzik', 'Apresiasi Muzik'],
    'Bahasa Arab': ['Bulan Masihi', 'Rumah Saya', 'Sayur-sayuran dan Buah-buahan', 'Nombor dan Bilangan']
  },
  'Tahun 5 (KSSR)': {
    'Bahasa Cina': ['Sejarah (历史)', 'Geografi (地理)', 'Masyarakat (社会)', 'Ekonomi (经济)'],
    'Bahasa Melayu': ['Kemasyarakatan', 'Kesihatan dan Kebersihan', 'Keselamatan', 'Sejarah, Warisan dan Budi Bahasa', 'Sains, Teknologi dan Inovasi'],
    'Bahasa Inggeris': ['Towns and cities', 'Days', 'Wild life', 'Learning world', 'Food and health', 'Sport', 'Growing up', 'Going away'],
    'Matematik': ['Nombor hingga 1,000,000', 'Pecahan, Perpuluhan dan Peratus', 'Wang', 'Masa dan Waktu', 'Ukuran dan Sukatan', 'Ruang', 'Koordinat, Nisbah dan Kadaran', 'Pengurusan Data'],
    'Sains': ['Kemahiran Saintifik', 'Manusia (Sistem Rangka, Sistem Peredaran Darah)', 'Haiwan (Kemandirian Spesies)', 'Tumbuh-tumbuhan (Kemandirian Spesies)', 'Elektrik', 'Haba', 'Karat', 'Jirim', 'Fasa Bulan dan Buruj', 'Mesin'],
    'Pendidikan Islam': ['Al-Quran: Surah Al-Qadr & Al-Tin', 'Tajwid: Hukum Idgham & Ikhfa', 'Jawi: Teks Berformat', 'Akidah: Beriman Kepada Hari Kiamat', 'Akidah: Nama Allah Al-Malik & Al-Hasib', 'Ibadah: Solat Berjemaah', 'Ibadah: Solat Jumaat', 'Sirah: Pembukaan Kota Mekah', 'Adab: Menjaga Kemudahan Awam', 'Adab: Jual Beli'],
    'Sejarah': ['Kedaulatan Negara', 'Perjuangan Kemerdekaan', 'Sejarah Kemerdekaan 1957', 'Yang di-Pertuan Agong', 'Identiti Negara'],
    'Reka Bentuk dan Teknologi': ['Asas Teknologi Pertanian', 'Reka Bentuk Artikel Jahitan', 'Pengaturcaraan (Mikropengawal)'],
    'Pendidikan Jasmani dan Pendidikan Kesihatan': ['Kemahiran Asas Permainan', 'Olahraga Asas', 'Gimnastik Asas', 'Pergerakan Berirama', 'Akuatik Asas', 'Rekreasi dan Kesenggangan', 'Kecergasan Fizikal', 'Kesihatan Diri dan Reproduktif (PEERS)', 'Pemakanan Sihat', 'Pertolongan Cemas'],
    'Pendidikan Seni Visual dan Pendidikan Muzik': ['Menggambar', 'Membuat Corak dan Rekaan', 'Membentuk dan Membuat Binaan', 'Mengenal Kraf Tradisional', 'Pengalaman Muzikal', 'Penghasilan Muzik', 'Apresiasi Muzik'],
    'Bahasa Arab': ['Aktiviti di Sekolah', 'Di Dapur', 'Makanan dan Minuman', 'Haiwan']
  },
  'Tahun 6 (KSSR)': {
    'Bahasa Cina': ['Patriotisme (爱国)', 'Pemimpin (领袖)', 'Kewangan (金融)', 'Sukan (运动)'],
    'Bahasa Melayu': ['Jati Diri, Patriotisme dan Kewarganegaraan', 'Sains, Teknologi dan Inovasi', 'Pertanian dan Penternakan', 'Ekonomi, Keusahawanan dan Kewangan', 'Alam Sekitar'],
    'Bahasa Inggeris': ['Emergency!', 'Life in the past', 'Adventure time', 'Cool jobs', 'Getting around', 'How is it made?', 'Music and song', 'Tell me a story'],
    'Matematik': ['Nombor Bulat dan Operasi', 'Pecahan, Perpuluhan dan Peratus', 'Wang', 'Masa dan Waktu', 'Ukuran dan Sukatan', 'Ruang', 'Koordinat, Nisbah dan Kadaran', 'Pengurusan Data dan Kebarangkalian'],
    'Sains': ['Kemahiran Saintifik', 'Manusia (Sistem Saraf)', 'Mikroorganisma', 'Interaksi Antara Hidupan', 'Pemeliharaan dan Pemuliharaan', 'Daya', 'Kelajuan', 'Pengawetan Makanan', 'Bahan Buangan', 'Gerhana', 'Buruj', 'Mesin'],
    'Pendidikan Islam': ['Al-Quran: Surah As-Sharh & Ad-Duha', 'Tajwid: Hukum Mad (Lanjutan)', 'Jawi: Seni Khat', 'Akidah: Beriman Kepada Qada & Qadar', 'Akidah: Nama Allah Al-Ghafur & Al-Tawwab', 'Ibadah: Solat Jenazah & Solat Sunat Aidilfitri/Aidiladha', 'Sirah: Perkembangan Islam Selepas Pembukaan Mekah', 'Adab: Sayangi Alam Sekitar', 'Adab: Rezeki Yang Halal'],
    'Sejarah': ['Pembentukan Malaysia', 'Pemimpin Negara', 'Kemakmuran Negara', 'Sukan Kebanggaan', 'Malaysia di Persada Dunia'],
    'Reka Bentuk dan Teknologi': ['Aplikasi Reka Bentuk', 'Reka Bentuk Elektromekanikal', 'Asas Pengaturcaraan Lanjutan'],
    'Pendidikan Jasmani dan Pendidikan Kesihatan': ['Kemahiran Asas Permainan', 'Olahraga Asas', 'Gimnastik Asas', 'Pergerakan Berirama', 'Akuatik Asas', 'Rekreasi dan Kesenggangan', 'Kecergasan Fizikal', 'Kesihatan Diri dan Reproduktif (PEERS)', 'Pemakanan Sihat', 'Pertolongan Cemas'],
    'Pendidikan Seni Visual dan Pendidikan Muzik': ['Menggambar', 'Membuat Corak dan Rekaan', 'Membentuk dan Membuat Binaan', 'Mengenal Kraf Tradisional', 'Pengalaman Muzikal', 'Penghasilan Muzik', 'Apresiasi Muzik'],
    'Bahasa Arab': ['Sukan dan Permainan', 'Pengangkutan', 'Bentuk', 'Cita-cita']
  },
  'Peralihan': {
    'Bahasa Melayu': ['Tema 1', 'Tema 2', 'Tema 3'],
    'Amalan Bahasa Melayu': ['Diri dan Keluarga', 'Masyarakat', 'Negara']
  },
  'Tingkatan 1 (KSSM)': {
    'Bahasa Melayu': ['Kesihatan dan Kebersihan', 'Keselamatan', 'Perpaduan', 'Kebudayaan, Kesenian dan Estetika', 'Jati Diri, Patriotisme dan Kewarganegaraan'],
    'Bahasa Inggeris': ['People and Culture', 'Health and Environment', 'Science and Technology', 'Consumerism and Financial Awareness'],
    'Matematik': ['Nombor Nisbah', 'Faktor dan Gandaan', 'Kuasa Dua, Punca Kuasa Dua, Kuasa Tiga dan Punca Kuasa Tiga', 'Nisbah, Kadar dan Kadaran', 'Ungkapan Algebra', 'Persamaan Linear', 'Ketaksamaan Linear', 'Garis dan Sudut', 'Poligon Asas', 'Perimeter dan Luas', 'Pengenalan Set', 'Pengendalian Data', 'Teorem Pythagoras'],
    'Sains': ['Pengenalan kepada Penyiasatan Saintifik', 'Sel sebagai Unit Asas Hidupan', 'Koordinasi dan Gerak Balas', 'Pembiakan', 'Jirim', 'Jadual Berkala', 'Udara', 'Cahaya dan Optik', 'Bumi'],
    'Pendidikan Islam': ['Al-Quran: Surah Al-Baqarah (Ayat 1-5, 201, 255-257, 284-286)', 'Hadis: Hadis 40 (Niat & Ikhlas)', 'Akidah: Beriman Kepada Allah', 'Akidah: Nama Allah Al-Khaliq & Al-Musawwir', 'Fikah: Konsep Ibadah', 'Fikah: Bersuci (Taharah)', 'Fikah: Solat Fardu', 'Sirah: Masyarakat Arab Sebelum Islam', 'Sirah: Riwayat Hidup Nabi Muhammad SAW', 'Akhlak: Akhlak Terpuji', 'Akhlak: Adab Menuntut Ilmu'],
    'Bahasa Arab': ['Taaruf', 'Keluarga', 'Sekolah', 'Hobi', 'Makanan'],
    'Sejarah': ['Mengenali Sejarah', 'Zaman Air Batu', 'Zaman Prasejarah', 'Tamadun Dunia dan Sumbangannya (Mesopotamia, Mesir, Indus, Huang He)', 'Tamadun Yunani, Rom, India & China'],
    'Asas Sains Komputer': ['Konsep Asas Pemikiran Komputasional', 'Perwakilan Data', 'Algoritma', 'Kod Arahan (Python/Scratch)'],
    'Reka Bentuk dan Teknologi': ['Pengenalan kepada Reka Bentuk', 'Pengurusan Projek', 'Proses Reka Bentuk', 'Lakaran', 'Aplikasi Reka Bentuk (Fertigasi / Fesyen)']
  },
  'Tingkatan 2 (KSSM)': {
    'Bahasa Melayu': ['Kesihatan dan Kebersihan', 'Meniti Alam Remaja', 'Dunia Sukan dan Rekreasi', 'Kerjaya', 'Sains, Teknologi dan Inovasi'],
    'Bahasa Inggeris': ['Health and Environment', 'People and Culture', 'Science and Technology', 'Consumerism and Financial Awareness'],
    'Matematik': ['Pola dan Jujukan', 'Pemfaktoran dan Pecahan Algebra', 'Rumus Algebra', 'Poligon', 'Bulatan', 'Bentuk Geometri Tiga Dimensi', 'Koordinat', 'Graf Fungsi', 'Laju dan Pecutan', 'Kecerunan Garis Lurus', 'Transformasi Isometri', 'Sukatan Kecenderungan Memusat', 'Kebarangkalian Mudah'],
    'Sains': ['Biodiversiti', 'Ekosistem', 'Nutrisi', 'Kesihatan Manusia', 'Air dan Larutan', 'Asid dan Alkali', 'Keelektrikan dan Kemagnetan', 'Daya dan Gerakan', 'Haba', 'Gelombang Bunyi', 'Bintang dan Galaksi', 'Sistem Suria', 'Meteoroid, Asteroid, Komet'],
    'Pendidikan Islam': ['Al-Quran: Surah Ali Imran (Ayat 8, 18, 26-27)', 'Hadis: Hadis 40 (Mencegah Kemungkaran)', 'Akidah: Beriman Kepada Malaikat & Kitab', 'Akidah: Nama Allah Al-Qadir & Al-Qawiy', 'Fikah: Solat Qasar & Jamak', 'Fikah: Puasa', 'Fikah: Zakat Fitrah', 'Sirah: Hijrah Nabi Ke Madinah', 'Sirah: Kepimpinan Nabi Muhammad SAW', 'Akhlak: Adab Berkawan', 'Akhlak: Adab Terhadap Ibu Bapa'],
    'Bahasa Arab': ['Cita-cita', 'Aktiviti Kokurikulum', 'Percutian', 'Perayaan', 'Bentuk Muka Bumi'],
    'Sejarah': ['Kerajaan Alam Melayu', 'Sistem Pemerintahan & Sosiobudaya Alam Melayu', 'Agama & Kepercayaan', 'Kejayaan Alam Melayu'],
    'Asas Sains Komputer': ['Sistem Nombor Perenambelasan', 'Pembangunan Algoritma', 'Kod Arahan', 'Pangkalan Data Asas'],
    'Reka Bentuk dan Teknologi': ['Penyelesaian Masalah Inventif', 'Reka Bentuk Mekanikal', 'Reka Bentuk Elektrik', 'Reka Bentuk Elektronik', 'Reka Bentuk Akuaponik', 'Reka Bentuk Makanan']
  },
  'Tingkatan 3 (KSSM)': {
    'Bahasa Melayu': ['Kerjaya', 'Sains, Teknologi dan Inovasi', 'Pendidikan dan Sukan', 'Bahasa dan Kesusasteraan', 'Sejarah dan Warisan'],
    'Bahasa Inggeris': ['People and Culture', 'Health and Environment', 'Science and Technology', 'Consumerism and Financial Awareness'],
    'Matematik': ['Indeks', 'Bentuk Piawai', 'Matematik Pengguna: Simpanan dan Pelaburan', 'Lukisan Berskala', 'Nisbah Trigonometri', 'Sudut dan Tangen bagi Bulatan', 'Pelan dan Dongakan', 'Lokus dalam Dua Dimensi', 'Garis Lurus'],
    'Sains': ['Rangsangan dan Gerak Balas', 'Respirasi', 'Pengangkutan', 'Kereaktifan Logam', 'Termokimia', 'Elektrik dan Kemagnetan', 'Tenaga dan Kuasa', 'Keradioaktifan', 'Cuaca Angkasa Lepas', 'Penerokaan Angkasa Lepas'],
    'Pendidikan Islam': ['Al-Quran: Surah Al-Araf, Al-Baqarah', 'Hadis: Hindari Dosa Besar', 'Akidah: Beriman Kepada Rasul', 'Fikah: Pengurusan Jenazah', 'Fikah: Solat Sunat (Tahajud, Dhuha)', 'Sirah: Perjanjian Hudaibiyah', 'Sirah: Pembukaan Kota Mekah', 'Akhlak: Pemaaf', 'Akhlak: Bersyukur'],
    'Bahasa Arab': ['Teknologi Maklumat', 'Tokoh', 'Sukan dan Rekreasi', 'Ekonomi', 'Kesihatan'],
    'Sejarah': ['Kedatangan Kuasa Luar', 'Pentadbiran Negeri-Negeri Selat', 'Pentadbiran Negeri-Negeri Melayu Bersekutu', 'Pentadbiran Negeri-Negeri Melayu Tidak Bersekutu', 'Tindak Balas Masyarakat Tempatan'],
    'Asas Sains Komputer': ['Konsep Asas Kriptografi', 'Algoritma Lanjutan', 'Kod Arahan', 'Pembangunan Sistem'],
    'Reka Bentuk dan Teknologi': ['Reka Bentuk Mekatronik', 'Penghasilan Produk']
  },
  'Tingkatan 4 (KSSM)': {
    'Bahasa Melayu': ['Merealisasikan Impian', 'Insan Terdidik, Negara Sejahtera', 'Memetik Bintang', 'Menjulang Harapan di Bumi Bertuah', 'Pendidikan untuk Semua'],
    'Bahasa Inggeris': ['People and Culture', 'Health and Environment', 'Science and Technology', 'Consumerism and Financial Awareness'],
    'Matematik': ['Fungsi dan Persamaan Kuadratik', 'Asas Nombor', 'Penaakulan Logik', 'Operasi Set', 'Rangkaian dalam Teori Graf', 'Ketaksamaan Linear dalam Dua Pemboleh Ubah', 'Graf Gerakan', 'Sukatan Serakan Data Tak Terkumpul', 'Kebarangkalian Peristiwa Bergabung', 'Matematik Pengguna: Pengurusan Kewangan'],
    'Matematik Tambahan': ['Fungsi', 'Fungsi Kuadratik', 'Sistem Persamaan', 'Indeks, Surd dan Logaritma', 'Janjang', 'Hukum Linear', 'Geometri Koordinat', 'Vektor', 'Penyelesaian Segi Tiga', 'Nombor Indeks'],
    'Sains': ['Langkah Keselamatan', 'Bantuan Kecemasan', 'Teknik Mengukur Parameter Kesihatan', 'Teknologi Hijau', 'Genetik', 'Sokongan, Pergerakan dan Pertumbuhan', 'Koordinasi Badan', 'Unsur dan Bahan', 'Kimia Industri', 'Kimia dalam Perubatan', 'Daya dan Gerakan', 'Tenaga Nuklear'],
    'Fizik': ['Pengukuran', 'Daya dan Gerakan I', 'Kegravitian', 'Haba', 'Gelombang', 'Cahaya dan Optik'],
    'Kimia': ['Pengenalan Kimia', 'Jirim dan Struktur Atom', 'Konsep Mol, Formula dan Persamaan', 'Jadual Berkala Unsur', 'Ikatan Kimia', 'Asid, Bes dan Garam', 'Kadar Tindak Balas', 'Bahan Buatan dalam Industri'],
    'Biologi': ['Pengenalan Biologi', 'Biologi Sel', 'Pergerakan Bahan Merentasi Membran', 'Komposisi Kimia dalam Sel', 'Metabolisme dan Enzim', 'Pembahagian Sel', 'Respirasi Sel', 'Sistem Respirasi', 'Nutrisi dan Sistem Pencernaan', 'Pengangkutan dalam Manusia dan Haiwan', 'Keimunan', 'Koordinasi dan Gerak Balas', 'Homeostasis', 'Sokongan dan Pergerakan', 'Pembiakan Seksual'],
    'Pendidikan Islam': ['Al-Quran: Surah Al-Anam 162-163', 'Hadis: Hindari Rasuah', 'Akidah: Beriman Kepada Hari Kiamat', 'Fikah: Haji dan Umrah', 'Fikah: Sembelihan, Korban & Akikah', 'Fikah: Muamalat Islam', 'Sirah: Era Pemerintahan Khulafa Ar-Rasyidin', 'Akhlak: Bersikap Benar', 'Akhlak: Adab Terhadap Orang Sakit'],
    'Bahasa Arab': ['Seni Bina', 'Kebudayaan', 'Pendidikan', 'Media Massa', 'Pelancongan'],
    'Sejarah': ['Warisan Negara Bangsa', 'Kebangkitan Nasionalisme', 'Konflik Dunia & Pendudukan Jepun', 'Persekutuan Tanah Melayu 1948', 'Ancaman Komunis & Darurat'],
    'Prinsip Perakaunan': ['Pengenalan Perakaunan', 'Klasifikasi Akaun', 'Dokumen Perniagaan', 'Buku Catatan Pertama', 'Lejar', 'Imbangan Duga', 'Penyata Kewangan'],
    'Ekonomi': ['Pengenalan kepada Ekonomi', 'Pasaran', 'Pendapatan dan Perbelanjaan Negara', 'Wang dan Institusi Kewangan'],
    'Perniagaan': ['Tujuan Perniagaan', 'Organisasi Perniagaan', 'Visi, Misi dan Objektif', 'Bahagian-bahagian Fungsian']
  },
  'Tingkatan 5 (KSSM)': {
    'Bahasa Melayu': ['Anda Bersih, Anda Sihat', 'Sukan dan Rekreasi', 'Kerjaya Meniti Jaya', 'Bersatu Kita Teguh', 'Pendidikan untuk Semua'],
    'Bahasa Inggeris': ['People and Culture', 'Health and Environment', 'Science and Technology', 'Consumerism and Financial Awareness'],
    'Matematik': ['Ubahans', 'Matriks', 'Insurans', 'Percukaian', 'Kekongruenan, Pembesaran dan Gabungan Transformasi', 'Nisbah dan Graf Fungsi Trigonometri', 'Sukatan Serakan Data Terkumpul', 'Pemodelan Matematik'],
    'Matematik Tambahan': ['Sukatan Membulat', 'Pembezaan', 'Pengamiran', 'Pilih Atur dan Gabungan', 'Taburan Kebarangkalian', 'Fungsi Trigonometri', 'Pengaturcaraan Linear', 'Kinematik Gerakan Linear'],
    'Sains': ['Mikroorganisma', 'Nutrisi dan Teknologi Makanan', 'Kelestarian Alam Sekitar', 'Kadar Tindak Balas', 'Sebatian Karbon', 'Elektrokimia', 'Cahaya dan Optik', 'Daya dan Tekanan', 'Teknologi Angkasa Lepas'],
    'Fizik': ['Daya dan Gerakan II', 'Tekanan', 'Elektrik', 'Keelektromagnetan', 'Elektronik', 'Fizik Nuklear', 'Fizik Kuantum'],
    'Kimia': ['Keseimbangan Redoks', 'Sebatian Karbon', 'Termokimia', 'Polimer', 'Kimia Konsumer dan Industri'],
    'Biologi': ['Organisasi Tisu Tumbuhan', 'Struktur dan Fungsi Daun', 'Nutrisi dalam Tumbuhan', 'Pengangkutan dalam Tumbuhan', 'Gerak Balas dalam Tumbuhan', 'Pembiakan Seks dalam Tumbuhan Bunga', 'Adaptasi Tumbuhan', 'Biodiversiti', 'Ekosistem', 'Kelestarian Alam Sekitar', 'Pewarisan', 'Variasi', 'Teknologi Genetik'],
    'Pendidikan Islam': ['Al-Quran: Surah At-Taubah (Ayat 128-129)', 'Hadis: Ciri-ciri Mukmin Berjaya', 'Akidah: Beriman Kepada Qada & Qadar', 'Fikah: Perkahwinan (Munakahat)', 'Fikah: Pengurusan Harta (Wasiat, Faraid)', 'Sirah: Era Kerajaan Bani Umaiyah', 'Sirah: Era Kerajaan Bani Abbasiyah', 'Akhlak: Adab Bermusafir', 'Akhlak: Tawaduk'],
    'Bahasa Arab': ['Politik dan Pentadbiran', 'Sains dan Teknologi', 'Ekonomi', 'Kesusasteraan', 'Isu-isu Semasa'],
    'Sejarah': ['Kedaulatan Negara', 'Perlembagaan Persekutuan', 'Raja Berperlembagaan', 'Sistem Persekutuan', 'Pembentukan Malaysia', 'Cabaran Selepas Pembentukan Malaysia', 'Dasar Kebudayaan dan Pendidikan'],
    'Prinsip Perakaunan': ['Perakaunan untuk Syarikat Saham', 'Kelab dan Persatuan', 'Rekod Tak Lengkap', 'Perakaunan Pengurusan', 'Sistem Maklumat Perakaunan'],
    'Ekonomi': ['Kestabilan Ekonomi', 'Dasar Ekonomi Kerajaan', 'Perdagangan Antarabangsa', 'Kadar Pertukaran Asing'],
    'Perniagaan': ['Pengurusan Sumber Manusia', 'Pengurusan Sumber Fizikal dan Teknologi', 'Rancangan Perniagaan']
  }
};
